apiVersion: v1
kind: Pod
metadata:
  name: mongohostpath
spec:
  containers:
  - image: mongo:3.6
    name: mongo
    volumeMounts:
    - mountPath: /data/db
      name: data
  volumes:
  - name: data
    hostPath:
      path: /data-db
